apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    sonarqube.org/project-key: com.jamf.team-red-dawg:Notifier
  description: Notifier is a Swift app which can post alert or banner notifications on macOS 10.15+ clients.
  name: notifier
  tags:
    - datajar
    - autoupdate
    - swift
spec:
  type: application
  lifecycle: production
  owner: zubry
  system: jamf-auto-update
  serviceTier: 5